model	#1
structure	ChimeraXvis/reference.pdb
structureADD	ChimeraXvis/query.pdb
attr_file	ChimeraXvis/attributeDGG.dat
length	130
attr	ddG
palette	YlOrRd
lighting	soft
transparency	70
background	gray
