<MyLayout>
    GridLayout:
        cols:1
        size: root.width-200, root.height-200
        pos: 100, 100
        Label:
            text: 'EnTree - delta delta G on a phylogenetic tree'
            font_size: 26
            size_hint: 0.5, 0.2
            bold: True
            color: 0.1, 0.8, 0.1, 1
        Label:
            text: 'GPL3 license - GA Babbitt Lab at Rochester Institute of Technology'
            font_size: 16
            size_hint: 0.3, 0.1    
        GridLayout:
            cols:1
            Image:
                source: 'maestro.png'
            GridLayout:
                cols:1 
                Label:
                    text: ''
                    font_size: 16
                    size_hint: 0.3, 0.1
                Button:
                    id: btn1
                    text: "create structural variants specified by alignment"   
                    on_press: btn1.background_color=(0.1, 0.1, 0.9, 1)
                    on_press: root.btn1()
                    bold: True
                    font_size: 20
                    size_hint: 0.5, 0.3
                    color: 0.1, 0.85, 0.85, 1
                Button:
                    id: btn2
                    text: "perform molecular dynamic simulation on variants"   
                    on_press: btn2.background_color=(0.1, 0.1, 0.9, 1)
                    on_press: root.btn2()
                    bold: True
                    font_size: 20
                    size_hint: 0.5, 0.3
                    color: 0.95, 0.5, 0.5, 1
                Button:
                    id: btn3
                    text: "deploy MAESTRO multi-agent stability prediction on variants"   
                    on_press: btn3.background_color=(0.1, 0.1, 0.9, 1)
                    on_press: root.btn3()
                    bold: True
                    font_size: 20
                    size_hint: 0.5, 0.3
                    color: 0.95, 0.95, 0.1, 1    
                Button:
                    id: btn4
                    text: "map predicted ddG values to reference structure"   
                    on_press: btn4.background_color=(0.1, 0.1, 0.9, 1)
                    on_press: root.btn4()
                    bold: True
                    font_size: 20
                    size_hint: 0.5, 0.3
                    color: 0.95, 0.5, 0.5, 1 
                Button:
                    id: btn5
                    text: "create ddG and dRMSF weighted trees"   
                    on_press: btn5.background_color=(0.1, 0.1, 0.9, 1)
                    on_press: root.btn5()
                    bold: True
                    font_size: 20
                    size_hint: 0.5, 0.3
                    color: 0.95, 0.95, 0.1, 1  
                
